### ISSUE TITLE
Anatomical region annotations

### ISSUE THREAD

**Issue by peicai** [BGI-DEV-REG/ARTISTA#2]
Hi, thank you for the wonderful database!

I have two questions about spatial clustering and annotation.

- In the colData, I found the "spatial_leiden_e30_s8" column. I'm wondering if you performed SNN-based clustering after integrating data from multiple sections? Are the cluster IDs consistent within a stage (e.g., 2DPI_1, 2DPI_2, and 2DPI_3) but not across different stages (e.g., 2DPI_1 and 5DPI_1)?

- Regarding anatomical regions, in Figure 1C (left top)and Figure S6A, you show 6 anatomical regions (DP, MP, LP, VZ, Striatum, and Septum) at various developmental stages. How were these regions labeled/matched based on "spatial_leiden_e30_s8"? Did you use the same method for the 7 injury-induced regeneration stages? Is it possible to obtain anatomical region annotations for the different regeneration stages?

Thank you for your help!
Best, Peiying

**Comment by renliangrui** [comment]
Hi, Peiying.
I am also working on problem 2 recently. Have you solved it? The manual annotations of Figure S6A do not seem to be shared.

**Comment by WangShuai-3** [comment]
I apologize for the very, very delayed response to this issue.

Regarding your first question, each SNN-based clustering computation is performed independently for each spatial chip.

As for your second question, please find the annotation table attached below.

Additionally, please note that we have only annotated brain regions for developmental stages and have not annotated brain regions for injury stages. However, you might be able to re-annotate using “spatial_leiden_e30_s8” based on Fig1/FigS6 if necessary.  If you encounter any questions during this process, please feel free to leave a comment here or contact me via email at wangshuai3@genomics.cn.

Best regards,
Shuai Wang

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">
</head>
<body>


Sample | Segmentation.Spatial.Cluster | Region
-- | -- | --
Injury_control_FP200000239BL_E3 | 0 | VLMC
Injury_control_FP200000239BL_E3 | 1 | Striatum
Injury_control_FP200000239BL_E3 | 2 | Septum
Injury_control_FP200000239BL_E3 | 3 | VZ
Injury_control_FP200000239BL_E3 | 4 | MP
Injury_control_FP200000239BL_E3 | 5 | LP
Injury_control_FP200000239BL_E3 | 6 | VZ
Injury_control_FP200000239BL_E3 | 7 | DP
Injury_control_FP200000239BL_E3 | 8 | Septum
Injury_control_FP200000239BL_E3 | 9 | LP?
Meta_telencephalon_rep1_DP8400015234BLB2_1 | 0 | Striatum
Meta_telencephalon_rep1_DP8400015234BLB2_1 | 1 | MP
Meta_telencephalon_rep1_DP8400015234BLB2_1 | 2 | Septum
Meta_telencephalon_rep1_DP8400015234BLB2_1 | 3 | LP
Meta_telencephalon_rep1_DP8400015234BLB2_1 | 4 | VZ
Meta_telencephalon_rep1_DP8400015234BLB2_1 | 5 | VLMC
Meta_telencephalon_rep1_DP8400015234BLB2_1 | 6 | DP
Meta_telencephalon_rep1_DP8400015234BLB2_1 | 7 | Septum
Meta_telencephalon_rep1_DP8400015234BLB2_1 | 8 | VLMC
Meta_telencephalon_rep1_DP8400015234BLB2_1 | 9 | VLMC
Stage54_telencephalon_rep2_DP8400015649BRD6_2 | 0 | Striatum
Stage54_telencephalon_rep2_DP8400015649BRD6_2 | 1 | VZ
Stage54_telencephalon_rep2_DP8400015649BRD6_2 | 2 | VLMC
Stage54_telencephalon_rep2_DP8400015649BRD6_2 | 3 | VZ
Stage54_telencephalon_rep2_DP8400015649BRD6_2 | 4 | Septum
Stage54_telencephalon_rep2_DP8400015649BRD6_2 | 5 | VZ
Stage54_telencephalon_rep2_DP8400015649BRD6_2 | 6 | LP
Stage54_telencephalon_rep2_DP8400015649BRD6_2 | 7 | VZ
Stage54_telencephalon_rep2_DP8400015649BRD6_2 | 8 | MP
Stage54_telencephalon_rep2_DP8400015649BRD6_2 | 9 | DP
Stage54_telencephalon_rep2_DP8400015649BRD6_2 | 10 | VLMC
Stage57_telencephalon_rep2_DP8400015649BRD5_1 | 0 | Striatum
Stage57_telencephalon_rep2_DP8400015649BRD5_1 | 1 | VZ
Stage57_telencephalon_rep2_DP8400015649BRD5_1 | 2 | VLMC
Stage57_telencephalon_rep2_DP8400015649BRD5_1 | 3 | MP
Stage57_telencephalon_rep2_DP8400015649BRD5_1 | 4 | VLMC
Stage57_telencephalon_rep2_DP8400015649BRD5_1 | 5 | DP
Stage57_telencephalon_rep2_DP8400015649BRD5_1 | 6 | VZ
Stage57_telencephalon_rep2_DP8400015649BRD5_1 | 7 | VZ
Stage57_telencephalon_rep2_DP8400015649BRD5_1 | 8 | Septum
Stage57_telencephalon_rep2_DP8400015649BRD5_1 | 9 | LP
Stage57_telencephalon_rep2_DP8400015649BRD5_1 | 10 | Striatum
Stage57_telencephalon_rep2_DP8400015649BRD5_1 | 11 | VZ
Stage57_telencephalon_rep2_DP8400015649BRD5_1 | 12 | VZ
Stage44_telencephalon_rep2_FP200000239BL_E4 | 0 | Striatum
Stage44_telencephalon_rep2_FP200000239BL_E4 | 1 | VZ
Stage44_telencephalon_rep2_FP200000239BL_E4 | 2 | VZ
Stage44_telencephalon_rep2_FP200000239BL_E4 | 3 | Septum
Stage44_telencephalon_rep2_FP200000239BL_E4 | 4 | VZ
Stage44_telencephalon_rep2_FP200000239BL_E4 | 5 | VZ
Stage44_telencephalon_rep2_FP200000239BL_E4 | 6 | MP&DP
Stage44_telencephalon_rep2_FP200000239BL_E4 | 7 | LP
Stage44_telencephalon_rep2_FP200000239BL_E4 | 8 | VLMC
Stage44_telencephalon_rep2_FP200000239BL_E4 | 9 | VLMC



</body>

</html>

**Comment by WangShuai-3** [comment]
I apologize for the very delayed response to this issue.

Regarding your first question, each SNN-based clustering computation is performed independently for each spatial chip.

As for your second question, unfortunately, we have searched extensively and have confirmed that the annotation table from that time has been lost. However, you might be able to re-annotate using “spatial_leiden_e30_s8” based on FigS6 if necessary. If you encounter any questions during this process, please feel free to leave a comment here or contact me via email at wangshuai3@genomics.cn.

Additionally, please note that we have only annotated brain regions for developmental stages up to adulthood and have not annotated brain regions for injury stages.

Best regards,
Shuai Wang

**Comment by renliangrui** [comment]
尊敬的王老师
您好！非常感谢您回复我的问题，这极大的促进了我对数据的理解。


然而，我还有一些小疑问需要您帮忙解答一下。


目前我刚开始接触空间转录组和Stereo-seq技术，按照我的理解，Stereo-seq可以同时产生高质量的基因表达数据和细胞空间位置信息，其中利用基因表达信息可以定义组织切片上的细胞类型；利用空间位置信息则可以确定细胞类型在组织切片上的分布。这个过程就得到了图C的右半部分的结果，对吗？


那图c左上角的domain identification是结合什么信息得到的？   根据论文中的描述，应该也是 基因表达+空间位置，但是不同的区室是如何划分的？他们的marker应该怎么确定？在我的研究中，我对区室的划分更感兴趣，所以想搞清楚每个区室应该怎么划分，还请王老师指点一下。


感谢您的回复


祝好
良瑞








| |
rlr
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 9/26/2024 18:00 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [BGI-DEV-REG/ARTISTA] Anatomical region annotations (Issue #2) |

Closed #2 as completed.

**Comment by WangShuai-3** [comment]
同学您好！

         SCC聚类同时考虑了细胞的基因表达上的邻居网络和空间位置上的邻居网络，因此在得到的聚类结果中，在同一块空间区域会混有不同细胞类型的细胞。被分为不同聚类的群，要么空间位置距离远，要么细胞组成差异大，导致基因上的关联小。脑区区室是真实的生理结构，一般认为不同区室空间上不重叠、细胞组成上具有差异，因此可以通过考虑SCC聚类和解剖学知识进行脑区注释。脑区不是均一细胞类型，无法用marker来定义，最多可以认为具有优势细胞类型。


祝好，

王帅

________________________________
发件人: renliangrui ***@***.***>
发送时间: 2024年9月27日 9:55:04
收件人: BGI-DEV-REG/ARTISTA
抄送: 王帅3(Shuai Wang); State change
主题: Re: [BGI-DEV-REG/ARTISTA] Anatomical region annotations (Issue #2)


外部邮件/External Mail




尊敬的王老师
您好！非常感谢您回复我的问题，这极大的促进了我对数据的理解。


然而，我还有一些小疑问需要您帮忙解答一下。


目前我刚开始接触空间转录组和Stereo-seq技术，按照我的理解，Stereo-seq可以同时产生高质量的基因表达数据和细胞空间位置信息，其中利用基因表达信息可以定义组织切片上的细胞类型；利用空间位置信息则可以确定细胞类型在组织切片上的分布。这个过程就得到了图C的右半部分的结果，对吗？


那图c左上角的domain identification是结合什么信息得到的？ 根据论文中的描述，应该也是 基因表达+空间位置，但是不同的区室是如何划分的？他们的marker应该怎么确定？在我的研究中，我对区室的划分更感兴趣，所以想搞清楚每个区室应该怎么划分，还请王老师指点一下。


感谢您的回复


祝好
良瑞








| |
rlr
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 9/26/2024 18:00 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [BGI-DEV-REG/ARTISTA] Anatomical region annotations (Issue #2) |

Closed #2 as completed.

―
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

―

**Comment by renliangrui** [comment]
感谢老师的回复。


现在我大概明白了。
首先，算法生成的细胞类型聚类，不一定是对的，需要根据实际情况，观察细胞组成或者考虑空间距离，对计算得到的聚类结果进行微调，使其更符合真实情况。
其次，区室的定义无法通过观察基因的高/低表达来定义，也无法通过聚类算法直接得到。

祝好 
良瑞 



| |
rlr
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 9/27/2024 10:24 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [BGI-DEV-REG/ARTISTA] Anatomical region annotations (Issue #2) |

同学您好！

SCC聚类同时考虑了细胞的基因表达上的邻居网络和空间位置上的邻居网络，因此在得到的聚类结果中，在同一块空间区域会混有不同细胞类型的细胞。被分为不同聚类的群，要么空间位置距离远，要么细胞组成差异大，导致基因上的关联小。脑区区室是真实的生理结构，一般认为不同区室空间上不重叠、细胞组成上具有差异，因此可以通过考虑SCC聚类和解剖学知识进行脑区注释。脑区不是均一细胞类型，无法用marker来定义，最多可以认为具有优势细胞类型。


祝好，

王帅

________________________________
发件人: renliangrui ***@***.***>
发送时间: 2024年9月27日 9:55:04
收件人: BGI-DEV-REG/ARTISTA
抄送: 王帅3(Shuai Wang); State change
主题: Re: [BGI-DEV-REG/ARTISTA] Anatomical region annotations (Issue #2)


外部邮件/External Mail




尊敬的王老师
您好！非常感谢您回复我的问题，这极大的促进了我对数据的理解。


然而，我还有一些小疑问需要您帮忙解答一下。


目前我刚开始接触空间转录组和Stereo-seq技术，按照我的理解，Stereo-seq可以同时产生高质量的基因表达数据和细胞空间位置信息，其中利用基因表达信息可以定义组织切片上的细胞类型；利用空间位置信息则可以确定细胞类型在组织切片上的分布。这个过程就得到了图C的右半部分的结果，对吗？


那图c左上角的domain identification是结合什么信息得到的？ 根据论文中的描述，应该也是 基因表达+空间位置，但是不同的区室是如何划分的？他们的marker应该怎么确定？在我的研究中，我对区室的划分更感兴趣，所以想搞清楚每个区室应该怎么划分，还请王老师指点一下。


感谢您的回复


祝好
良瑞








| |
rlr
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 9/26/2024 18:00 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [BGI-DEV-REG/ARTISTA] Anatomical region annotations (Issue #2) |

Closed #2 as completed.

―
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

―
